name: abg_pos_app
description: "A point of sale system for Aroma business group."
publish_to: 'none'

version: 1.0.12+31

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  internet_connection_checker: ^3.0.1
  get_storage: ^2.1.1
  logger: ^2.5.0
  jwt_decoder: ^2.0.1
  path_provider: ^2.1.5
  flutter_svg: ^2.2.0
  intl: ^0.20.2
  flutter_svg_provider: ^1.0.7
  collection: ^1.19.1
  dotted_border: ^3.1.0
  toggle_switch: ^2.3.0
  image_picker: ^1.1.2
  mime: ^2.0.0
  flutter_launcher_icons: ^0.14.4
  bluetooth_print_plus: ^2.4.6
  permission_handler: ^12.0.1
  flutter_image_compress: ^2.4.0
  excel: ^4.0.6
  file_saver: ^0.3.1
  path: ^1.9.1
  file_picker: ^10.3.3
  share_plus: ^12.0.0
  firebase_core: ^4.1.0
  firebase_remote_config: ^6.0.1
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/logo_small.png
    - assets/images/batmanpos_bw.png
    - assets/png/profile-placeholder.png
    - assets/svg/img-placeholder.svg
    - assets/svg/profile-placeholder.svg

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/poppins/Poppins-Italic.ttf
          style: italic

